### ISSUE TITLE
Nvidia support

### ISSUE THREAD

**Issue by ProducerMatt** [gbtb/nix-stable-diffusion#1]
I have an Nvidia GPU, if you put up an Nvidia branch I'd happily test it for you. In the meantime I'll take a jab at converting it myself, but I've never worked with a flake like this before so idk how far I'll get on it.

**Comment by gbtb** [comment]
Hello.

On a first glance it seems that it is only required to override torch with cudaSupport=true. Here is draft PR - https://github.com/gbtb/nix-stable-diffusion/pull/2. I've made two variants, with and without mkl - `nix develop .#invokeai-nvidia-mkl` and `nix develop .#invokeai-nvidia`. Unfortunately, I can't confirm that this shells even build, because of some timeout errors when downloading magma (probably my ISP is messing it up). But you can try it nevertheless :smiley:

**Comment by ProducerMatt** [comment]
Wow, it worked first try! Thank you :)

**Comment by gbtb** [comment]
Great! Btw, which one of the devshells worked for you - with or without mkl?

**Comment by ProducerMatt** [comment]
Both of them appear to work! But what does MKL change?

**Comment by gbtb** [comment]
> Both of them appear to work! But what does MKL change?

It changes blas implementation, it appears there is a [bug](https://github.com/NixOS/nixpkgs/issues/196653) in opencv4 that causes conflict of two incompatible blas versions. On my machine invokeai works only if I replace blas in opencv4 with different provider. 

Thank you for the testing! I will clean up my PR a little bit and merge into master.

**Comment by gbtb** [comment]
PR merged, slightly changed shell name - `nix develop .#invokeai.nvidia`
