### ISSUE TITLE
Tries to build something with pip ("No module named pip")

### ISSUE THREAD

**Issue by turion** [gbtb/nix-stable-diffusion#11]
After applying the patches manually (#8) and setting `HSA_OVERRIDE_GFX_VERSION=10.3.0` (#7), I'm facing this issue:

```
nix-stable-diffusion/stable-diffusion-webui]$ HSA_OVERRIDE_GFX_VERSION=10.3.0 python launch.py 
Python 3.10.7 (main, Sep  5 2022, 13:12:31) [GCC 11.3.0]
Commit hash: 737eb28faca8be2bb996ee0930ec77d1f7ebd939
Installing requirements for Web UI
Traceback (most recent call last):
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 205, in <module>
    prepare_enviroment()
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 188, in prepare_enviroment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 62, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/home/turion/python/nix-stable-diffusion/stable-diffusion-webui/launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "/nix/store/wyhbl43ycqn43d08v5fqj1j6ynf7nz73-python3-3.10.7/bin/python" -m pip install -r requirements_versions.txt --prefer-binary
Error code: 1
stdout: <empty>
stderr: /nix/store/wyhbl43ycqn43d08v5fqj1j6ynf7nz73-python3-3.10.7/bin/python: No module named pip
```
It seems that it still wants to install dependencies for webui. I would have expected these to be installed by the `nix develop` shell.

**Comment by gbtb** [comment]
Yep, that's again a symptom of broken or not applied patch.. You can see this exact line commented out [here](https://github.com/gbtb/nix-stable-diffusion/blob/d3beaef05759913b24310e79e7990f6251df36a9/webui.patch), because  all required deps are installed through flake.
I've used a manual patch instead of proper commit inside of a submodule because you can't commit to the submodule from the main repo and therefore you have to fork a submodule which is not what I want to do. Another approach would be to use some string substitution from inside nix build hook, but it is hard to do for a nix devshell.

**Comment by turion** [comment]
Thank you, I didn't apply the patch correctly, it turned out. Now it seems to start and download a lot of stuff. I think in principle patching is fine, it's just weird that something is messed up with the line endings (maybe LF vs CRLF?).
