### ISSUE TITLE
Updating/adding dependencies

### ISSUE THREAD

**Issue by atagen** [gbtb/nix-stable-diffusion#16]
Hi,

I'm trying to update the automatic1111 UI to the [latest commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/44c46f0ed395967cd3830dd481a2db759fda5b3b). This should provide nice benefits like sd2.0 support, sizeable reduction in VRAM use, and up to 1.5x reported inference speed increase from transformers library.

I'm more than happy to try taking on the packaging and updating of additional libraries here myself, but pynixify documentation is quite sparse, and it doesn't understand `git+...` syntax, so I don't understand how you achieved packaging `k-diffusion`, for example (obviously the nix file itself is simple enough but I'd like to follow the correct workflow). 

Would you be able to provide any guidance on your preferred way to achieve this with pynixify? I'm happy to figure out the rest of the bump, and I intend to continue updating for my own use as long as SD has my interest :)

Also, sorry if it's inappropriate to be making an issue for this - I did try to find you on some community hubs but without luck.

Thanks!

**Comment by gbtb** [comment]
Hello :wave:  Github issues definitely could be used for such kinds of questions and actually have an advantage of better discoverability over most other platforms, especially messengers.

I can share my workflow with you, no problem :)
When updating packages, I start with comparing versions and finding relevant differences. Since there is no releases or tags in Automatic repo that can be use for that purpose, necessary url with diff could be constructed manually - https://github.com/AUTOMATIC1111/stable-diffusion-webui/compare/737eb28faca8be2bb996ee0930ec77d1f7ebd939..44c46f0ed395967cd3830dd481a2db759fda5b3b
Firstly, looking into requirements.txt, there is addition of 4 new packages. GitPython is already present in nixpkgs, other 3 are not. 
For those 3 `pynixify` could be used, however official GitHub version follows an unfortunate "fail-fast" policy and doesn't tolerate any packages it could not resolve. I've made a quick-hack patch to allow `pynixify` to skip these errors - https://github.com/gbtb/pynixify. With patched version, you may pass all 3 missing packages at once or do them one by one. If all packages are present in pypi.org and have simple setup.py, then it should just work. If some package is not present in pypi, then you should clone it and run `pynixify` on it like it's a local package (in that case you'll have to manually replace src definition with fetchFromGitHub). Either way, at the end folders with nix definitions from pynixify/ should be copied to [nix-stable-diffusion](https://github.com/gbtb/nix-stable-diffusion) repo and hooked into a flake.nix
There are also some shenanigans with mismatching names of packages in nix and pypi, that's why I had to use `pythonRemoveDeps `and also manually pass `opencv-python = self.opencv4;` for some packages.

**Comment by atagen** [comment]
Hello, it's been a while! just a quick update.

I think I have [managed most of this](https://github.com/atagen/nix-stable-diffusion), but I have two blockers:

- scikit-image seems to cause a segfault on launch, haven't found a solution to this
- xformers (which is optional but improves speed) has a dependency on triton, which uses a python cmake build system I am struggling to work with

I have no expectation for anyone to pick this up but if they are so inclined feel free.
I will probably take a break from trying to fix the former issue until SD2.x becomes a bit more of a "must have", but I'd really love to knock the latter down since xformers is basically a universal speed boost.

I will PR if I manage to get this squeaky clean, but will otherwise refrain from closing this issue for now to keep the work visible to anyone searching around.

Thanks for your help with the packaging workflow, it was invaluable :)

**Comment by gbtb** [comment]
Hello, @atagen 
I'm curious about this segfault, what does error message and stack trace looks like? Because in the beginning I've also had a segfault related to blas/lapack incompatibility currently present in nixpkgs, maybe they share the same cause - https://github.com/NixOS/nixpkgs/issues/196653

**Comment by valconius** [comment]
@atagen I dont know how to use github so this is probably not a good place to contact you but anyway I worked on your repository, got things working for myself, and thought I'd write out a few notes.

- The latest webui commit works (same as is the default in your repository), though a few things had to be changed, they're somewhere in my git commits' history or whatever, I hardly know how to use the git tool
- I did not run into a segfault with scikit-image, but I _am_ using AMD ROCM, not Nvidia CUDA
- I have not tried cpu-only; is that even possible?
- Your flake.nix defaults to using Nvidia CUDA always. I stripped that out to make things work for me, but I haven't the slightest clue how the Nix language works, so I don't know how to programmatically toggle between CUDA, ROCM and CPU.
- Your webui.patch incorrectly has the nix-store paths hardcoded, easy enough to fix.
- I had to delete references to "safetensors" throughout the webui repository, thereafter everything worked (i.e. run `python launch.py --no-half` together with the correct YAML file for v2.1 checkpoints, oddly I could never get the v2.0 base checkpoint to work but the other 2.0 checkpoints seem to be fine).
- Unlike on Nvidia, AMD ROCM only provides out-of-the-box support for the "highest-end" gpu model, the engineering name for the marketing name'd RX 6900 is gfx1030. Making this work on an RX 6600 (gfx1032) requires `export HSA_OVERRIDE_GFX_VERSION=10.3.0`. Actually making it work well without extreme memory pressures requires manually compiling pytorch and, presuambly, pytorch-vision for gfx1032 through random instructions I found on the internet in the attached image. Were this Guix I would kinda know where to start, but I haven't the foggiest clue where to start on Nix.
![Screenshot 2022-12-18 at 13-39-21 r_Amd - Here's something you don't see every day PyTorch running on top of ROCm on a 6800M (6700XT) laptop! Took a ton of minor config tweaks - instructions for pytorch compilation gfx1032 rx6600](https://user-images.githubusercontent.com/4463623/208344441-c45155fb-9176-4b88-90ac-805d5092692b.png)
- There is an additional frustration on ROCM. Since PyTorch uses the MIOpen library from ROCM's HIP's whatevers, a precompiled database file **for the GPU model the PyTorch compiled binaries were specifically compiled with** (gfx1030 by default, ignore that bit in the above image) is expected somewhere under `/opt/amdgpu/...`. If this file is not available (it isn't for me), webui spends about 2 minutes only at the very first image generation presumably generating some substitute for provisional use. The full warning, where image gen pauses until this provisional compilation occurs, is:
```shell
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
  0%|                                                                                | 0/20 [00:00<?, ?it/s]
MIOpen(HIP): Warning [SQLiteBase] Missing system database file: gfx1030_14.kdb Performance may degrade. Please follow instructions to install: https://github.com/ROCmSoftwarePlatform/MIOpen#installing-miopen-kernels-package
```

My continued annoyance since yesterday, since before I ran into your repository, is the **safetensors' package's use of the rust compiler**. I provide a not-working, hapless and haplessly-created `default.nix` for your perusal below, meant to go into `packages/safetensors/default.nix` together with the requisite changes to `flake.nix' to actually use the package.

```nix
{ lib
, buildPythonPackage
, fetchPypi
, huggingface-hub
, black
, isort
, flake8
, click
, torch
, numpy
  ### ?
#, tensorflow
, setuptools-rust
, h5py
  ### ?
#, jax
#, flax
  ### ? Rust compiler not found -> so i guess i add the compiler
, rustc
, cargo
}:

buildPythonPackage rec {
  pname = "safetensors";
  version = "0.2.5";

  src = fetchPypi {
    inherit pname version;
    sha256 = "sha256-ifBSfITcwsyX4X7/KfTmQU9+d+zkHMyrTx+wYCv1GTE=";
  };

  propagatedBuildInputs = [
    huggingface-hub
    numpy
    black
    isort
    flake8
    click
    torch
    ### ?
    #tensorflow
    #setuptools-rust
    #h5py
    ### ?
    #jax
    #flax
    ### ? Rust compiler not found -> so i guess i add the compiler
    #rustc
    #cargo
  ];

  doCheck = false; # TODO Enable tests

  meta = with lib; {
    homepage = "https://github.com/google-research/torchsde";
    description = "PyTorch implementation of differentiable SDE solvers";
    license = licenses.bsd3;
  };
}
```

**Comment by gbtb** [comment]
I've released new version of the flake, with updated webui, but without triton (which seems optional). Feel free to try it out :)
